### PR TITLE
修正資料庫連線不穩定問題

### PR DESCRIPTION
**Pull request by rdcvgt**
老師好，因爲部分檔案出現問題所以開了新的 repository
姓名：彭勝緯

測試網址：
http://13.112.131.32:3000/api/attraction/3
http://13.112.131.32:3000/api/categories
http://13.112.131.32:3000/api/attractions?page=1&keyword=梅
http://13.112.131.32:3000/api/attractions?page=4
http://13.112.131.32:3000/api/attractions?page=40
http://13.112.131.32:3000/api/attractions?page=1fsdf

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Re-request review after you solve issues below:

1.
nextPage field should be null if there is no more pages. I mean nextPage field of http://13.112.131.32:3000/api/attractions?page=4 should be null.

2.
We should use keyword to filter all attractions and paginate them. If there are 14 attractions after filtering, we get only 2 pages. If there are 4 attractions after filtering, we get only 1 page containing all of these 4 attractions.

3.
http://13.112.131.32:3000/api/attractions?page=0&keyword=%E5%8F%B0 should have some data there.

**Comment by rdcvgt** [comment]
老師好，已經修正上述問題，再麻煩查看，謝謝！

**Review by cwpeng — CHANGES_REQUESTED** [review]
1.
If we search keyword 台 in attraction name, http://13.112.131.32:3000/api/attractions?page=1&keyword=%E5%8F%B0 should have some data there.

2.
For general, one page should contains 12 attractions. http://13.112.131.32:3000/api/attractions?page=1

**Comment by cwpeng** [comment]
Sorry for issue 1. You are right. My judgement is not correct.

Just fix for issue 2.

**Comment by rdcvgt** [comment]
Hi teacher, thanks for the reminder, I've fixed for issue 2.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result looks OK but it's bad practive to do pagination depends on id because id is not always continuous number, id only means unique.

It's much better to use `LIMIT` in SQL to do pagination.

Solve this issue and re-request review.

**Comment by rdcvgt** [comment]
Hi teacher,  I've changed the way I write the sql sentence, please have a look, thanks.

**Review by cwpeng — APPROVED** [review]
OK. Done. You are in the first five. :)

**Comment by rdcvgt** [comment]
Many thanks!

**Pull request merged**
